# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SP', 'Spatial Pointing Task'), ('TP', 'Temporal Pointing Task'), ('STP', 'Spatial-Temporal Pointing Task')], default='SP', max_length=3)),
                ('env', jsonfield.fields.JSONField()),
            ],
        ),
    ]
