# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='mode',
            field=models.CharField(choices=[('SP', 'Spatial Pointing Task'), ('TP', 'Temporal Pointing Task'), ('STP', 'Spatial-Temporal Pointing Task')], default='SP', max_length=3, unique=True),
        ),
    ]
