# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mode',
            field=models.CharField(choices=[('SP', 'Spatial Pointing Task'), ('TP', 'Temporal Pointing Task'), ('STP', 'Spatial-Temporal Pointing Task')], default='SP', max_length=3),
        ),
    ]
