# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointing', '0004_auto_20170524_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='logs',
            new_name='data',
        ),
    ]
